### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by tomquisel** [stellar/awesome-stellar#2]
This is fantastic! Here are a bunch of ideas:

- Developer resources is long. Maybe break it up. Developer Educational resources could be a different section?
- Link to the official Stellar Wallets list
- List out selected SEPs, like SEP-1 and SEP-6. There's a SEP-1 validator out there, and also a rudimentary SEP-6 validator. Link to those. SEP-7 Also has some example links out in the wild at id.stellar.expert and Keybase has some [examples](https://keybase.io/docs/cajaqx/lvcg/sep7links)
- Include the Stellar Lab and account viewer
- Mention Cowrie, the NGNT anchor
- Add more developer tools, there are a bunch out there
    - [Stellar burrito](https://github.com/stellarburrito/stellarburritojs)
- Maybe have a contribute section that links to contribution guides and getting started guides for Horizon, Core, etc...
- Link to the Ticker's [GraphIQL](https://ticker.stellar.org/graphiql), it's a great resource
- I'm not sure Smartlands should be on the anchor list, they don't anchor any tokens
- Consider adding Stellarport, interstellar.exchange, NaoBTC, and the white wallet as anchors

**Comment by 0xKolten** [comment]
Hey Tom, thanks for all of these!

> Link to the official Stellar Wallets list 

Is this list going to remain the same after we switch to: https://beta.stellar.org/lumens/wallets? 

> Add more developer tools, there are a bunch out there

Agree, Rob thought of this section yesterday so I'll be digging some up.
