### ISSUE TITLE
Add more to Developer "Useful Tools" Section

### ISSUE THREAD

**Issue by robertDurst** [stellar/awesome-stellar#5]
I think there are surely some more useful tools out there.

Opening an issue so I can link to it in the Stellar Dev Digest.

**Comment by 0xKolten** [comment]
Perfect, thanks!

**Comment by MisterTicot** [comment]
Cosmic.plus libraries: https://cosmic.plus/#libraries

- cosmic-lib: implement CosmicLink & SEP-0007.
- ledger-wallet: Ledger Wallets support in two lines of code.
- loopcall: Limitless/advanced queries to horizon.
- oc-multisig: On-chain multisig account coordination.

Cosmic.plus applications: https://cosmic.plus/#applications

- Equilibre.io: wallet-independent portfolio balancer for Stellar (first app to use delegated signing)
- Cosmic.link: CosmicLink protocol frontend.
- Stellar Authenticator: Security-oriented wallet. (+ useful dev tool)

**Comment by MisterTicot** [comment]
Cosmic.link/SEP-0007 debugger: https://cosmic.plus/js-cosmic-lib/web/demo
